### ISSUE TITLE
插件代码疑问

### ISSUE THREAD

**Issue by zzyzzyzx** [thanple/HotSecondsIDEA#11]
想问下这个插件部分的代码有开源吗，好像没找到是怎么将修改后的代码上传到server的那部分代码

**Comment by Liubsyy** [comment]
目前还没有开源，这个工程只是存了一些文档和安装包

**Comment by Liubsyy** [comment]
不过扩展项目HotSeconds Extension是开源的

**Comment by jinglekang** [comment]
> 目前还没有开源，这个工程只是存了一些文档和安装包

原来没开源呀。。。

**Comment by zzyzzyzx** [comment]
> 目前还没有开源，这个工程只是存了一些文档和安装包

大佬有计划开源吗

**Comment by slieer** [comment]
Sonic是美团内部一款用于热部署的IDEA插件。据说很不错的，可以参考。
https://tech.meituan.com/2022/03/17/java-hotswap-sonic.html
