### ISSUE TITLE
下面是我本地部署的流程,但是提示报错异常

### ISSUE THREAD

**Issue by YuanEr2** [thanple/HotSecondsIDEA#12]
1.去[dcevm](https://github.com/dcevm/dcevm/releases) 找到你的JDK版本的jar包(支持macOS, Linux and Windows)，下载下来后运行jar（可能需要管理员权限或者root权限）安装，选择Install DCEVM as altjvm
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/63f56456-2885-44ca-ab41-c431edaeee8c)

2.将本安装包[HotSecondsServer.zip](https://github.com/thanple/HotSecondsIDEA/blob/master/install/download_server.md)解压后，放到你的工程根目录
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/80ab72b8-059c-4798-8f70-2097a87dbe8f)

3.将hot-seconds-remote.xml复制到代码的resource目录，根据需要修改secret和classloader等配置
第一步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/a46e1879-e122-4e20-8839-4015fc5d0b1b)

第二步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/368b8672-f49b-4aa1-ba46-32270ae2936f)

第三步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/f60c30d3-cb6d-4993-83de-75da2af541aa)

第四步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/8ec6dded-bc0b-4fd8-84e1-f61c240b8adb)

4.添加jvm参数开启热部署代理
 -XXaltjvm=dcevm -javaagent:$path1/HotSecondsServer.jar=hotconf=$path2/hot-seconds-remote.xml
其中$path1是第2步上传的目录，$path2是第3步上传的目录
第一步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/d02df357-eef1-4008-b034-1ea5a326f11f)

第二步:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/8539a3ec-4108-4d0e-b382-c1e8de08cd00)

异常信息:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/dd25fdc3-8ff3-4fc9-a7b7-700fd0dd041e)

**Comment by YuanEr2** [comment]
当我把Jvm参数改为:
-XXaltjvm=dcevm -javaagent:HotSecondsServer-beat4.HotSecondsServer.jar=hotconf=com.parent.modules.hot-seconds-remote.xml
报错异常更改为:
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/ea3f0f9a-284b-4575-b43f-ba46284b86a4)

**Comment by Liubsyy** [comment]
最近有好几个小伙伴反馈windows上缺失依赖库，我把所有的静态依赖都打包到了boot.dll了，发布了HotSecondsServer-beat5版本，你下载这个版本试一下应该就没问题了，我找了外行妹子的电脑试了没问题

**Comment by Liubsyy** [comment]
你的操作没有什么问题，就按最开始的配置就行

**Comment by YuanEr2** [comment]
下载HotSecondsServer-beat5版本后,我按照最开始的配置部署,存在下面新的问题
1.Jvm参数设置为时:
-XXaltjvm=dcevm -javaagent:HotSecondsServer-beat5/HotSecondsServer.jar=hotconf=com/parent/modules/hot-seconds-remote.xml
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/004a60fc-042a-4540-965a-557dbfdf6317)

2.Jvm参数设置为时:
-XXaltjvm=dcevm -javaagent:HotSecondsServer-beat5.HotSecondsServer.jar=hotconf=com.parent.modules.hot-seconds-remote.xml
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/cb5948c4-6c55-4361-91b8-6e544f818326)

**Comment by YuanEr2** [comment]
而且当我在Windows使用cmd测试时也显示没有主属性清单
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/31754b26-2b27-44d1-9a17-6d661ee75a57)

**Comment by Liubsyy** [comment]
hotconf填的是hot-seconds-remote.xml的路径，不是相对src的路径也不是包名，写绝对路径也可以的，其实hot-seconds-remote.xml随便放哪里都无所谓，只需要hotconf配置上路径就行

> 下载HotSecondsServer-beat5版本后,我按照最开始的配置部署,存在下面新的问题 1.Jvm参数设置为时: -XXaltjvm=dcevm -javaagent:HotSecondsServer-beat5/HotSecondsServer.jar=hotconf=com/parent/modules/hot-seconds-remote.xml ![image](https://user-images.githubusercontent.com/125980642/262190674-004a60fc-042a-4540-965a-557dbfdf6317.png)
> 
> 2.Jvm参数设置为时: -XXaltjvm=dcevm -javaagent:HotSecondsServer-beat5.HotSecondsServer.jar=hotconf=com.parent.modules.hot-seconds-remote.xml ![image](https://user-images.githubusercontent.com/125980642/262190883-cb5948c4-6c55-4361-91b8-6e544f818326.png)

**Comment by YuanEr2** [comment]
现在项目可以启动了,但是热部署时出现编译失败
![image](https://github.com/thanple/HotSecondsIDEA/assets/125980642/58bcff31-73d5-4e60-b656-685935b7a94f)

**Comment by Liubsyy** [comment]
另外本地的main函数启动的SpringBoot项目是AppClassLoader，不是LaunchedURLClassLoader

**Comment by YuanEr2** [comment]
springBoot项目没有问题，现在出问题的是springBootCloud项目，使用了gateway,nacos,mybtis-plus等技术栈

**Comment by Liubsyy** [comment]
这个报错就是hot-seconds-remote.xml填的classloader未找到，所以报空指针异常，你可以在你要热加载的类上面断点调试一下，用getClass().getClassLoader()看看classloader是哪个，然后填到hot-seconds-remote.xml里，因为热加载某个类是由classloader+classname才能确定唯一的一个class，所有的class热更新都需要这个classloader.

**Comment by Liubsyy** [comment]
之所以需要手动填classloader而不是插件自动扫描的原因是，把依赖框架和容器的依赖classloader剥夺出来，无论什么容器都能热部署
