### ISSUE TITLE
dcevm.so 版本与 服务器 jdk版本 必须一致吗

### ISSUE THREAD

**Issue by 1994syc** [thanple/HotSecondsIDEA#14]
All dcevm.so downloads 列表中没用我需要的版本 ：1.8.0_40

**Comment by Liubsyy** [comment]
不是必须的但是最好一致，不然运行不稳定，另外你这个jdk版本比较老，可以考虑升级一下版本，如果不能升级，可以试一下这个补丁[libjvm_so_8u45](https://github.com/thanple/HotSecondsIDEA/releases/download/libjvm_so_8u45/libjvm.so)，放到./lib目录下覆盖原文件即可

**Comment by 1994syc** [comment]
好的，感谢。我试试
