### ISSUE TITLE
本地项目启动报错

### ISSUE THREAD

**Issue by LEE1632718991** [thanple/HotSecondsIDEA#20]
启动控制台报错信息：
![image](https://github.com/thanple/HotSecondsIDEA/assets/108018769/94f15e49-d76a-47e5-bb2c-457d58601304)
jvm参数： -XXaltjvm=dcevm -javaagent:D:\tests\datasendtest\path1\HotSecondsServer.jar=hotconf=D:\tests\datasendtest\path2\hot-seconds-remote.xml

![image](https://github.com/thanple/HotSecondsIDEA/assets/108018769/6f6b47b3-87a6-47b0-9b67-703e6a413e5a)
![image](https://github.com/thanple/HotSecondsIDEA/assets/108018769/174f2785-2c70-41c8-9497-41bd2865bfcb)
麻烦大佬们帮我看看怎么回事？

**Comment by Liubsyy** [comment]
jdk版本和dcevm版本是一致的吗？你输入java -XXaltjvm=dcevm -version能出来吗

**Comment by LEE1632718991** [comment]
![image](https://github.com/thanple/HotSecondsIDEA/assets/108018769/0c900771-5dd0-4a9e-a884-c937854f7c00)

**Comment by LEE1632718991** [comment]
![image](https://github.com/thanple/HotSecondsIDEA/assets/108018769/640fd50f-6ac6-4a48-90ee-8f97906005bb)
好了😂
