### ISSUE TITLE
Failed to connect?

### ISSUE THREAD

**Issue by nidehehe** [thanple/HotSecondsIDEA#4]
Failed to connect to remote 192.168.51.201:2023 Connection refused to host: 127.0.0.1; nested exception is: java.net.ConnectException: Connection refused: connect
Server端在虚拟机上部署成功且端口正常。

**Comment by Liubsyy** [comment]
那估计是你本地和192.168.51.201:2023网络不通，你可以试试nc -zv 192.168.51.201 2023 或者 telnet一下看看

**Comment by nidehehe** [comment]
提问题前我已经确认了端口是没问题的，0.0。
![image](https://github.com/thanple/HotSecondsIDEA/assets/23652205/9d535561-f29b-4b28-a82b-ebbea53f1328)
![image](https://github.com/thanple/HotSecondsIDEA/assets/23652205/da3cbf16-6cc2-4ced-bb7c-376acc9587ba)
![image](https://github.com/thanple/HotSecondsIDEA/assets/23652205/a080f916-3bb8-4842-ae8a-665c67bd7caf)

**Comment by Liubsyy** [comment]
虚拟机网络的问题，你用的是哪种网络模式？是NAT模式么？

**Comment by Liubsyy** [comment]
虚拟机网络的问题，你用的是哪种网络模式？是NAT模式么？

**Comment by nidehehe** [comment]
支持Maven多模块吗？

**Comment by bd7xzzxyz** [comment]
> Failed to connect to remote 192.168.51.201:2023 Connection refused to host: 127.0.0.1; nested exception is: java.net.ConnectException: Connection refused: connect Server端在虚拟机上部署成功且端口正常。

应该是死锁了吧，2023端口压根没起来

**Comment by nanxing7** [comment]
我也是连不上
