### ISSUE TITLE
支持Maven多模块吗？

### ISSUE THREAD

**Issue by Liubsyy** [thanple/HotSecondsIDEA#5]
支持Maven多模块吗？

_Originally posted by @nidehehe in https://github.com/thanple/HotSecondsIDEA/issues/4#issuecomment-1612541718_
            
如果多模块都部署在一个服务器上，目前是支持的，如果多个模块部署的服务器不一样，目前还未支持，可以多开几个IDEA窗口也能做到。
后期我也是想支持的，就是一个IDEA窗口下可以连接多个不同项目的服务器，但是我不想把配置和操作设计的繁琐，尽可能简单。

**Comment by Liubsyy** [comment]
看看有没有好的想法，尽可能的简单操作，而不是启动还得选模块选IP，太繁琐了对使用快捷键也不友好，也不方便

**Comment by nidehehe** [comment]
赞
