### ISSUE TITLE
请确保启动 Java 进程的用户和 Host 登陆用户一致

### ISSUE THREAD

**Issue by CloudwiseAI** [thanple/HotSecondsIDEA#8]
我远程服务器上用的不是root启动的服务，就报这个错：
热部署连接失败：请确保启动 Java 进程的用户和 Host 登陆用户一致

**我想把服务器登录的用户名改一下**，可是在哪修改远程服务器的配置呢，只能添加，不能删除和修改

**Comment by Liubsyy** [comment]
你直接切换到java进程的用户启动就行了
一般不会出现这个问题，不知道你是不是中间切换过运行的用户

**Comment by osramywj** [comment]
> 
直接切换到java进程的用户启动，你指的启动远程java进程？不行，你可以试试，远程使用非root启动java项目，本地连不上服务器。

而且那个添加主机的地方，只能加，不能删除和修改，加过一个host，host就不能重复了，死路了

**Comment by Liubsyy** [comment]
@osramywj 我这边都是非root启动的java项目都没问题，能不能把完整的部署启动流程和异常贴一下呢？甚至是源码或者脚本也可以把敏感信息去掉贴一下，越详细越好，现在信息量太少理解不对称
