### ISSUE TITLE
设置服务器参数后生成的客户端xml文件中文乱码

### ISSUE THREAD

**Issue by jinglekang** [thanple/HotSecondsIDEA#9]
* 操作系统：Windows
* 默认编码：UTF-8

> 相关设置：

![image](https://github.com/thanple/HotSecondsIDEA/assets/17934343/732ad598-1d6b-4c86-850e-7d279f1c32c2)
![image](https://github.com/thanple/HotSecondsIDEA/assets/17934343/f1777653-3309-44be-90d8-e273e8f534e4)
![image](https://github.com/thanple/HotSecondsIDEA/assets/17934343/4ff9e424-2323-40b3-adca-daeee799aa44)

**Comment by Liubsyy** [comment]
影响不大，只是个注释，直接用Run->HotSeconds Settings->Settings配置就行，后续优化下windows下注释问题

**Comment by jinglekang** [comment]
已解决
